/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.jpsocket.client;

import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.FileInputStream;
import java.io.IOException;
import java.net.Socket;

import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author k4lfer
 */
public class JFClient extends javax.swing.JFrame implements Runnable{
    private String name;
    private Socket socket;
    private DataInputStream input;
    private DataOutputStream output;


    /**
     * Creates new form JFClient
     */
    public JFClient() {
        initComponents();
        jTFInputMessage.setEditable(false);
        jBttnSend.setEnabled(false);
        jTxtPMessageArea.setEditable(false);
        jTxtPMessageArea.setContentType("text/html");
    }


    // Conectar al servidor
    private void connect() {
        try {
            socket = new Socket("0.0.0.0", 9999); // Conectar al servidor en localhost y puerto 9999
            input = new DataInputStream(socket.getInputStream()); // Stream de entrada
            output = new DataOutputStream(socket.getOutputStream()); // Stream de salida
            output.writeUTF(name); // Enviar el nombre del usuario

            Thread thread = new Thread(this); // Crea un nuevo hilo
            thread.start(); // Hilo que escucha mensajes del servidor

        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "No se pudo conectar al servidor: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    // Enviar mensaje al servidor
    private void enviarMensaje() {
        try {
            output.writeUTF(jTFInputMessage.getText() + "\n"); // Envía el mensaje al servidor con el nombre del usuario
            jTFInputMessage.setText(""); // Limpia el campo de entrada de mensaje
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Error al enviar mensaje: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void addBubble(String message) {

    }

    private void updateUserTable(String listData) {
        String[] rows = listData.split(",");
        String[][] data = new String[rows.length][2];

        for (int i = 0; i < rows.length; i++) {
            if(!rows[i].isEmpty()) {
                data[i][0] = rows[i];
                data[i][1] = "Online";
            }
        }

        jTable1.setModel(new DefaultTableModel(
            data,
            new String[]{"Users", "Status"}
        ));
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBttnSend = new javax.swing.JButton();
        jTFInputMessage = new javax.swing.JTextField();
        jTFName = new javax.swing.JTextField();
        jBttnRegister = new javax.swing.JButton();
        jBttnLoadFile = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTxtPMessageArea = new javax.swing.JTextPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jBttnSend.setText("Send");
        jBttnSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBttnSendActionPerformed(evt);
            }
        });

        jTFName.setToolTipText("");

        jBttnRegister.setText("Register");
        jBttnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBttnRegisterActionPerformed(evt);
            }
        });

        jBttnLoadFile.setText("Load File");
        jBttnLoadFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBttnLoadFileActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(jTxtPMessageArea);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Al", "online"},
                {"fer", "online"},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Users", "Status"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTFName, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(jBttnRegister))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jTFInputMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBttnSend))
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(jBttnLoadFile)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTFName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBttnRegister))
                        .addGap(15, 15, 15)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFInputMessage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBttnSend)
                    .addComponent(jBttnLoadFile))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBttnSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBttnSendActionPerformed
        enviarMensaje();
    }//GEN-LAST:event_jBttnSendActionPerformed

    private void jBttnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBttnRegisterActionPerformed
        // TODO add your handling code here:
        name = jTFName.getText().trim();
        if(name.isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Please enter your name", "Error", JOptionPane.ERROR_MESSAGE);
        }
        else
        {
            jTFName.setEditable(false);
            jBttnRegister.setEnabled(false);
            jTFInputMessage.setEditable(true);
            jBttnSend.setEnabled(true);
            connect(); // Llama al método para conectar al servidor
        }
    }//GEN-LAST:event_jBttnRegisterActionPerformed

    private void jBttnLoadFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBttnLoadFileActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        int result = fileChooser.showOpenDialog(this);

        if (result == JFileChooser.APPROVE_OPTION) {
            java.io.File selectedFile = fileChooser.getSelectedFile();

            try (FileInputStream fileInput = new FileInputStream(selectedFile)) {
                // Enviar nombre y tamaño primero
                output.writeUTF("FILE"); // comando para indicar que se enviará un archivo
                output.writeUTF(selectedFile.getName()); // Nombre del archivo
                output.writeLong(selectedFile.length()); // Tamaño del archivo

                // Enviar contenido en fragmentos
                byte[] buffer = new byte[4096];
                int bytesRead;
                while ((bytesRead = fileInput.read(buffer)) != -1) {
                    output.write(buffer, 0, bytesRead);
                }
                output.flush(); // Asegura que todos los datos se envíen

                JOptionPane.showMessageDialog(this, "Archivo enviado exitosamente.");

            } catch (IOException ex) {
                JOptionPane.showMessageDialog(this, "Error al enviar el archivo: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jBttnLoadFileActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        // Obtener el usuario seleccionado
        if (jTable1.getSelectedRow() == -1) {
            return; // No hay fila seleccionada
        }
        var selectRow = jTable1.getSelectedRow();// Obtiene la fila seleccionada 
        String selectedUser = (String) jTable1.getValueAt(selectRow, 0); // Obtiene el nombre del usuario seleccionado
             
        System.out.println("Position: "+jTable1.getValueAt(selectRow, 0));
    }//GEN-LAST:event_jTable1MouseClicked



    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFClient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBttnLoadFile;
    private javax.swing.JButton jBttnRegister;
    private javax.swing.JButton jBttnSend;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTFInputMessage;
    private javax.swing.JTextField jTFName;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextPane jTxtPMessageArea;
    // End of variables declaration//GEN-END:variables
    
    @Override
    public void run() {
        try {
            while (!socket.isClosed()) { // Mientras el socket no esté cerrado
                // Lee el mensaje enviado por el servidor
                String msg = input.readUTF();
                if (msg.startsWith("USERLIST:")) {
                    updateUserTable(msg.substring(9));
                }
                else{
                    jTxtPMessageArea.setText(msg);
                    jTxtPMessageArea.setCaretPosition(jTxtPMessageArea.getDocument().getLength());
                }
                
                //String currentText = jTxtPMessageArea.getText();
                //String newText = currentText + "<br>" + msg;
                
                //addBubble(msg);
        
            }
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Conexión perdida: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        } finally { // Bloque finally para cerrar recursos
            // Cierra los streams de entrada y salida
            try {
                if (socket != null) socket.close(); // Cierra el socket
            } catch (IOException ignored) {
                JOptionPane.showMessageDialog(this, "Error al cerrar la conexión: " + ignored.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            } 
        }
    }
}
